name: Build and Test

on: 
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./backend.Tests.sln # Adjust the solution path if needed

      - name: Build solution
        run: dotnet build --no-restore ./backend.Tests.sln

      - name: Run unit tests
        run: dotnet test ./backend.Tests/backend.Tests.csproj --filter "FullyQualifiedName~Unit"

      - name: Run integration tests
        run: dotnet test ./backend.Tests/backend.Tests.csproj --filter "FullyQualifiedName~Integration"